# Generated by Django 5.2.6 on 2025-09-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_SYSTEM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('EVENT', 'Event'), ('UPCOMING', 'Upcoming'), ('NEWS', 'News')], default='NEWS', max_length=20)),
                ('short_text', models.TextField()),
                ('full_text', models.TextField()),
                ('image', models.ImageField(upload_to='news_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
