# Generated by Django 5.2.6 on 2025-09-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_SYSTEM', '0002_gallerycategory_remove_galleryimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
