# Generated by Django 5.2.6 on 2025-09-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_SYSTEM', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('NEWS', 'News'), ('EVENT', 'Event'), ('UPCOMING', 'Upcoming')], max_length=20),
        ),
    ]
