# Generated by Django 5.2.6 on 2025-09-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_SYSTEM', '0003_alter_news_options_news_updated_at_alter_news_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('NEWS', 'News'), ('EVENT', 'Event'), ('UPCOMING', 'Upcoming')], default='NEWS', max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
