# Generated by Django 5.2.6 on 2025-09-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_SYSTEM', '0004_alter_news_options_alter_news_full_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='news/default.jpg', upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('NEWS', 'News'), ('EVENT', 'Event'), ('UPCOMING', 'Upcoming')], max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
