# Generated by Django 5.2.6 on 2025-09-25 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_SYSTEM', '0007_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='CMS_SYSTEM.gallerycategory'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery_images/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
