# Generated by Django 5.2.6 on 2025-09-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_SYSTEM', '0010_serviceinfrastructure_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='serviceinfrastructure',
            name='link',
            field=models.URLField(blank=True, default='/area'),
        ),
        migrations.AlterField(
            model_name='whychooseservices',
            name='icon',
            field=models.CharField(help_text="Emoji or class name (e.g. '🌊' or 'fa fa-icon')", max_length=50),
        ),
    ]
