# Generated by Django 5.2.6 on 2025-10-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_SYSTEM', '0013_service_delete_serviceinfrastructure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('pub_type', models.CharField(choices=[('Journal Article', 'Journal Article'), ('Conference Paper', 'Conference Paper'), ('Book Chapter', 'Book Chapter'), ('Report', 'Report'), ('Other', 'Other')], default='Other', max_length=50)),
                ('date_published', models.DateField()),
                ('abstract', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='publications/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-date_published', '-created_at'],
            },
        ),
    ]
