# Generated by Django 5.2.6 on 2025-10-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_SYSTEM', '0015_organizationstructurefile_orgnode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationstructurefile',
            name='pdf',
        ),
        migrations.AddField(
            model_name='organizationstructurefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='organization_structure/'),
        ),
        migrations.AddField(
            model_name='organizationstructurefile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('image', 'Image')], max_length=10),
        ),
        migrations.AddField(
            model_name='organizationstructurefile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='OrgNode',
        ),
    ]
