# Generated by Django 5.2.6 on 2025-10-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_SYSTEM', '0017_homeevent_homeimpactoverview_homemarinesection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homevicechancellormessage',
            name='video_url',
        ),
        migrations.AddField(
            model_name='homevicechancellormessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='vc/videos/'),
        ),
        migrations.AlterField(
            model_name='homevicechancellormessage',
            name='image',
            field=models.ImageField(upload_to='vc/images/'),
        ),
    ]
